### ISSUE TITLE
Dev mode toggle

### ISSUE THREAD

**Issue by missmatsuko** [lukeyouell/craft3-sentry#11]
I saw this in the README roadmap and would love to see it implemented.

We tried using [Overriding Plugin Settings](https://github.com/lukeyouell/craft-sentry#overriding-plugin-settings) to disable Sentry errors on dev. However, the settings seem to be cached in the database anyways so we are currently manually disabling the Sentry plugin after every pull-down from production.

**Comment by lukeyouell** [comment]
I've added a new config setting that should solve this.

If you add `'enabled' => false,` in your `sentry.php` config file the plugin won't report errors to Sentry. This can be set per-environment.

**Comment by lukeyouell** [comment]
(this change is available in the latest release)
