### ISSUE TITLE
Problem with 1.5.0 release

### ISSUE THREAD

**Issue by jamesmacwhite** [lukeyouell/craft3-sentry#17]
Hi @lukeyouell.

I think something happened when creating the latest release. The `enabled` option appears to have been added in 1.4.0, but then disappeared in the 1.5.0 release, looking at the git commits.

Any chance a new release can be created?

**Comment by lukeyouell** [comment]
@jamesmacwhite this setting has been reinstated and released - sorry about that!

**Comment by jamesmacwhite** [comment]
@lukeyouell No worries. Thanks for the re-release!
