### ISSUE TITLE
FR: Sentry JS error reporting

### ISSUE THREAD

**Issue by jamesmacwhite** [lukeyouell/craft3-sentry#19]
Hi @lukeyouell,

Coming from a Craft 2 project, we used a Craft 2 Sentry plugin which loaded Raven JS which could track JS related exceptions/errors. Raven.js has since been deprecated in favour of the Unified Browser JavaScript SDK:

https://docs.sentry.io/error-reporting/quickstart/?platform=browser

Do you think it would be possible for this plugin to support loading the Sentry JS SDK on the front end to capture these errors?

Thanks!

**Comment by lukeyouell** [comment]
This isn't something the plugin will be covering as it can be achieved without it. You just need to load the script and use your dot env value wherever you load it as per the Sentry docs.
