### ISSUE TITLE
Sentry is not getting the statusCode when twig catch the exception.

### ISSUE THREAD

**Issue by blasvicco** [lukeyouell/craft3-sentry#7]
In [here](https://github.com/lukeyouell/craft-sentry/blob/b8bc5dc57f6cab0c3cfef63a3055ea562ec76985/src/services/SentryService.php#L95) Sentry is just looking for the property `statusCode` but if the exception is triggered from the twig file like
```TWIG
{% exit 404 %}
```

Then the exception that arrive to the event hook is `Twig_Error_Runtime` that has not a `statusCode` property.

Suggestion is look for the `Twig_Error_Runtime->getPrevious()` to get the proper `yii\web\HttpException` that is the one that has the `statusCode` property.

**Comment by mwarkentin** [comment]
@lukeyouell Any thoughts on this? Just playing around with setting up sentry on a craft project and seems like a large source of potential errors that we'd miss if the twig stuff isn't picked up.

**Comment by lukeyouell** [comment]
Thanks!
